### ISSUE TITLE
Add parallel

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#12]
Is it difficult to parallel computation for a few arguments?
```
jsize jquery lodash lodash/map @rill/http/adapter/document
```

To calc them in parallel?

**Comment by DylanPiercey** [comment]
I thought of doing this, although the problem is it is non-deterministic if you install all of them at once to the same folder (unless npm has drastically changed). Essentially you have to create a temp folder for each package being installed, which at times (esp in the case of stuff like `lodash/map lodash/assign lodash/map` this would actually download lodash 3 times instead of once.

Could be worth digging further into though, I just didn't find it to be worth it.
