### ISSUE TITLE
Add css loader

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/jsize#34]
Will be cool to have a simple css loader to be able to get size of stuff like _react-toolbox_.

**Comment by DylanPiercey** [comment]
I feel like this might be more of a pain than it's worth.

Firstly webpack is completely changing how CSS is handled in webpack 4. It would also complicate the UI because we wouldn't know if we needed to render a CSS section until after compiling (unless we just included it in the size of the js bundle).
Also most people preprocess CSS which means that it'd only help in a small number of cases.

**Comment by antonmedv** [comment]
Nice reason, okay
